### ISSUE TITLE
Add links or mention the other GRASS presentations in the Intro session

### ISSUE THREAD

**Issue by veroandreo** [veroandreo/grass_opengeohub2019#2]
Could be a separate slide before the "thanks for yor attention" one... I think it's a nice way to super briefly explain what the other presentations will be about and awake some interest :)

What do you say @neteler?

**Comment by neteler** [comment]
Sounds great. We may reuse fractions of this text:

Actinia ([https://actinia.mundialis.de](https://actinia.mundialis.de/)) is an open source REST API for scalable, distributed, high performance processing of geographical data that uses mainly GRASS GIS for computational tasks. Core functionality includes the processing of single and time series of satellite images, of raster and vector data. With the existing (e.g. Landsat) and Copernicus Sentinel big geodata pools which are growing day by day, actinia is designed to follow the paradigm of bringing algorithms to the cloud stored geodata. Actinia is an OSGeo Community Project since 2019.

**Comment by veroandreo** [comment]
I just added a note in the "thanks" slide, felt like it would cut the flow otherwise
